name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make defconfig
      run: make defconfig
    - name: install dependencies
      run: sudo apt install -y build-essential gcc-multilib flex bison libncurses5-dev pkg-config libglade2-dev libssl-dev libelf-dev
    - name: make
      run: make -j$(nproc)
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: linux-kernel-x86-bzImage
        path: arch/x86/boot/bzImage
